food_homepage:
    path:     /
    defaults: { _controller: FoodBundle:Default:bestand } 
    
food_login:
    path:     /login
    defaults: { _controller: FoodBundle:Security:login }
  
food_bestand:
    path:     /bestand
    defaults: { _controller: FoodBundle:Default:bestand } 

food_jsonbestand:
    path:     /jsonbestand
    defaults: { _controller: FoodBundle:Default:jsonbestand }
    
food_jsonbestand:
    path:     /jsonbestand
    defaults: { _controller: FoodBundle:Default:jsonbestand }
    
food_new:
    path:     /bestand/neu
    defaults: { _controller: FoodBundle:Default:neu }
    

food_neuesEssen:
    path:     /bestand/neues-lebensmittel
    defaults: { _controller: FoodBundle:Default:neuesEssen }
    
food_abgang:
    path:     /bestand/{id}
    defaults: { _controller: FoodBundle:Default:abgang }    
    
shoppinglist:
    path:     /shoppinglist
    defaults: { _controller: FoodBundle:Default:shoppinglist }    
    
shoppinglist_add:
    path:     /shoppinglist/add
    defaults: { _controller: FoodBundle:Default:addlist }  
    
shoppinglist_delete:
    path:     /shoppinglist/delete/{id}
    defaults: { _controller: FoodBundle:Default:deletelist }  
   
